library( stats )
mytree <- read.table( "R.full.matrix" )
postscript( "cluster.raw.ps", width=8, height=8, horizontal=FALSE, paper="letter" )
hc <- hclust( log( as.dist( mytree ) ), method="average")
plot( hc, main="Structural Clustering", ylab="Structural Distance", xlab="", labels=c(
"[1] (((((((..)))))))",
"[2] ((((((....))))))",
"[3] .((((((..)))))).",
"[4] .((((((..).)))))",
"[5] ((((((...).)))))",
"[6] .(((((...)..))))",
"[7] .(((((....))))).",
"[8] .(((((.(..))))))",
"[9] ((((((..))))))..",
"[10] .(((((.....)))))",
"[11] .((((((..))).)))",
"[12] .(((((....).))))",
"[13] ((((((...))))))."
))
dev.off()
quit()
